[package]
name = "redstone_sdk"
version = "1.0.0"
authors = []

[addresses]
redstone_sdk="_"

[dev-addresses]
redstone_sdk="0xedeed"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-node-v1.34.3-hotfix"
subdir = "aptos-move/framework/aptos-framework"
