[package]
name = "redstone_sdk"
version = "1.0.0"
authors = []

[addresses]
redstone_sdk="_"

[dev-addresses]
redstone_sdk="0xedeed"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"
