[workspace]
resolver = "2"
members = [
    "rust-sdk",
    "price_adapter",
    "price_feed",
    "proxy",
    "badge_creator"
]

[profile.release]
opt-level = 'z'        # Optimize for size.
lto = true             # Enable Link Time Optimization.
codegen-units = 1      # Reduce the number of codegen units to increase optimizations.
panic = 'abort'        # Abort on panic.
strip = true           # Strip the symbols.
overflow-checks = true # Panic in the case of an overflow.
