services:
  operator-attester:
    image: public.ecr.aws/y7v2w8b2/avs-othentic-client:e54c10e1
    platform: linux/amd64
    command: [
        "node",
        "attester",
        "/ip4/54.220.62.139/tcp/3000/p2p/12D3KooWSBMPURmCU5B8nuXkUw1Tq26FuvDg5LsEcs4WX8dqAxWJ",
        "--avs-webapi",
        "http://operator-validation-api",
        "--avs-webapi-port",
        "4002",
        "--p2p.port",
        "3000",
        "--l1-chain",
        "mainnet",
        "--l2-chain",
        "base",
        "--p2p.datadir",
        ".othentic/data/p2p",
        # "--announced-addresses",
        # "${ANNOUNCED_ADDRESSES}",
      ]
    env_file:
      - .env
    volumes:
      - .othentic:/app/.othentic
    ports:
      - "3000:3000"
  operator-validation-api:
    image: public.ecr.aws/y7v2w8b2/avs-validation-api:4fe497a6
    platform: linux/amd64
