services:
  operator-attester:
    image: public.ecr.aws/y7v2w8b2/avs-othentic-client:4fb59875
    platform: linux/amd64
    command:
      [
        "node",
        "attester",
        "/dns/prod-aggregator1-p2p.a.redstone.finance/tcp/3000/p2p/12D3KooWSBMPURmCU5B8nuXkUw1Tq26FuvDg5LsEcs4WX8dqAxWJ",
        "--avs-webapi",
        "http://operator-validation-api",
        "--avs-webapi-port",
        "4002",
        "--p2p.port",
        "3000",
        "--l1-chain",
        "mainnet",
        "--l2-chain",
        "base",
        "--p2p.datadir",
        ".othentic/data/p2p"
      ]
    env_file:
      - .env
  operator-validation-api:
    image: public.ecr.aws/y7v2w8b2/avs-validation-api:4fb59875
    platform: linux/amd64
