[package]
edition = "2021"
name = "redstone-adapter"
publish = false
version = "1.0.0"

[lib]
crate-type = ["cdylib", "lib"]
doctest = false

[dependencies]
common = { workspace = true }
hex-literal = { workspace = true }
redstone = { workspace = true, default-features = false, features = [
  "soroban",
] }
soroban-sdk = { workspace = true, features = ["alloc"] }

[dev-dependencies]
hex = { workspace = true }
redstone_testing = { workspace = true }
soroban-sdk = { workspace = true, features = ["testutils"] }
