[workspace]
members = ["common", "contracts/*"]
resolver = "2"

[workspace.dependencies]
common = { path = "common" }

hex = "0.4.3"
hex-literal = { version = "1.0.0" }
redstone = { git = "https://github.com/redstone-finance/rust-sdk", tag = "3.0.0-pre5", default-features = false }
redstone-testing = { git = "https://github.com/redstone-finance/rust-sdk", tag = "redstone-testing-v0.3.3" }
soroban-sdk = "23.0.2"

[profile.release]
codegen-units = 1
debug = 0
debug-assertions = false
lto = true
opt-level = "z"
overflow-checks = true
panic = "abort"
strip = "symbols"

# For more information about this profile see https://soroban.stellar.org/docs/basic-tutorials/logging#cargotoml-profile
[profile.release-with-logs]
debug-assertions = true
inherits = "release"
