[project]
authors = ["≈Åukasz Kalbarczyk"]
entry = "main.sw"
forc-version = "0.65.2"
license = "Apache-2.0"
name = "demo"
organization = "RedStone"

[dependencies]
redstone = { path = "../redstone-fuel-sdk" }
