[project]
authors = ["≈Åukasz Kalbarczyk"]
entry = "main.sw"
forc-version = "0.65.2"
license = "Apache-2.0"
name = "contract_invoker_core"
organization = "RedStone"

[dependencies]
common = { path = "../common" }
